### PR TITLE
Create AnimationType class to define player animations

### PR DESCRIPTION
**Pull request by KnosTx**

### CODE REVIEW

**Comment by IvanCraft623** [comment]
What does this have to do with BedrockProtocol?

**Comment by xpocketmc** [comment]
1. **Necessity for `BedrockProtocol`**: The code defining animation types (e.g., `SWIM`, `WALK`) is indeed necessary if the server or client using `BedrockProtocol` needs to handle or transmit information about various player animations. `BedrockProtocol` requires clear definitions for animation types to function correctly.

2. **Code Function**: This code provides standardized names for different animation types, which are essential for accurate communication between the server and client.

3. **Implementation**: If `BedrockProtocol` in PocketMine-MP involves handling player animations, then this code is a critical part of that implementation.

**Comment by dktapps** [comment]
> 1. **Necessity for `BedrockProtocol`**: The code defining animation types (e.g., `SWIM`, `WALK`) is indeed necessary if the server or client using `BedrockProtocol` needs to handle or transmit information about various player animations. `BedrockProtocol` requires clear definitions for animation types to function correctly.
> 2. **Code Function**: This code provides standardized names for different animation types, which are essential for accurate communication between the server and client.
> 3. **Implementation**: If `BedrockProtocol` in PocketMine-MP involves handling player animations, then this code is a critical part of that implementation.

gtfo with your AI generated drivel

**Comment by IvanCraft623** [comment]
@NurAzliYT Please provide what's this for

**Pull request closed without merging**
